---
apiVersion: v1
kind: Secret
metadata:
  name: vault-creds
  namespace: vault
type: Opaque
stringData:
  credentials: |
    {
      "token_name": "root-token",
      "token": "hvs.7IWgypqHkICYufCjO27hQtsc"
    }
---
apiVersion: vault.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: vault-provider-config
spec:
  address: http://vault.vault.svc.cluster.local:8200
  credentials:
    source: Secret
    secretRef:
      name: vault-creds
      namespace: vault
      key: credentials
